/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdt.chuong03.dohoa.frames;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdt.chuong03.coffeelogic.CoffeeShop;
import lthdt.chuong03.coffeelogic.Manager;

/**
 *
 * @author FPT
 */
public class MyCoffee extends javax.swing.JInternalFrame {
    
    

    /**
     * Creates new form MyCoffee
     */
    public MyCoffee() throws ParseException {
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        
        CoffeeShop[] a = new CoffeeShop[]{ new CoffeeShop("Kha Coffee","2 Nguyen Hue" ),
                                           new CoffeeShop("White Garden", "4 Nguyen Hue" ),
                                           new CoffeeShop("Hoa Truc Vien", "3 Nguyen Hue")};
        Manager[] managers = new Manager[]{ 
                             new Manager(a, 0, "Le Thi A", 0, df.parse("12-12-1999")),
                             new Manager(new CoffeeShop[]{
                              new CoffeeShop("Hoang Hac", "12 Nguyen Hue")
                                      },
                                     2000, "Nguyen Van B", 1, df.parse("12-12-2000"))
                             };
        for (int i = 0; i < managers.length; i++ ){
            cbnguoiquanly.addItem(managers[i].getHoten());
        }
        
        //DefaultTableModel model = (DefaultTableModel) tbcoffee.getModel();
        //model.setRowCount(0);
        //CoffeeShop[] shops = managers[0].getShops();
        //for(int i = 0; i < shops.length; i++){
            //model.insertRow(model.getRowCount(),
                    //new Object[]{model.getRowCount() + 1,
                                  //shops[i].getName(),
                                  //shops[i].getAddress()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcoffee = new javax.swing.JTable();
        cbnguoiquanly = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setTitle("Danh Sach Cac Quan Cafe");

        jLabel1.setText("Ho Ten Nguoi Quan Ly ");

        tbcoffee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ten Quan", "Dia Chi"
            }
        ));
        jScrollPane1.setViewportView(tbcoffee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(cbnguoiquanly, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbnguoiquanly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbnguoiquanly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbcoffee;
    // End of variables declaration//GEN-END:variables






}
