 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdt.chuong03.dohoa.frames;

import java.awt.Graphics2D;
import java.util.Random;

/**
 *
 * @author FPT
 */
public class XuatDuLieuFrame extends javax.swing.JInternalFrame {
    int [] a;

    /**
     * Creates new form XuatDuLieuFrame
     */
    public XuatDuLieuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnpanel = new javax.swing.JPanel();
        butvemang1chieu = new javax.swing.JButton();
        butsapxep = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ve Du Lieu Mang 1 Chieu");

        javax.swing.GroupLayout pnpanelLayout = new javax.swing.GroupLayout(pnpanel);
        pnpanel.setLayout(pnpanelLayout);
        pnpanelLayout.setHorizontalGroup(
            pnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        pnpanelLayout.setVerticalGroup(
            pnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        butvemang1chieu.setText("Ve Mang 1 Chieu Ra Man Hinh");
        butvemang1chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butvemang1chieuActionPerformed(evt);
            }
        });

        butsapxep.setText("Sap Xep Mang 1 Chieu");
        butsapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsapxepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butvemang1chieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butsapxep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butvemang1chieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butsapxep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butvemang1chieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butvemang1chieuActionPerformed
        // TODO add your handling code here:
        Graphics2D gr = (Graphics2D) pnpanel.getGraphics();
        int maxX = pnpanel.getWidth();
        int maxY = pnpanel.getHeight();
        int step = 5 ;
        int n  = maxX/step;
        a = new int[n];
        Random rnd = new Random();
        for (int i =0 ; i<n; i++){
            a[i] = rnd.nextInt(maxY);
        }
        int beginX = 0, beginY = 0;
        gr.clearRect(0, 0, maxX, maxY);
        for(int i =0 ; i < n; i++){
            //gr.drawRect(beginX, beginY, step, a[i]);
            gr.drawRect(beginX, maxY - a[i], step, a[i]);
            beginX += step;
            
        }
        
    }//GEN-LAST:event_butvemang1chieuActionPerformed

    private void butsapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsapxepActionPerformed
        // TODO add your handling code here:
        Graphics2D gr = (Graphics2D) pnpanel.getGraphics();
        int maxX = pnpanel.getWidth();
        int maxY = pnpanel.getHeight();
        int step = 5 ;
        int n  = maxX/step;
        int beginX=0;int beginX2 = 0;
        for (int i = 0;i<n-1;i++){
            for(int j=i;j<n;j++){
                if(a[i]>a[j]){
                    int temp = a[i];
                    //xoa hinh a[i] cu
                    gr.clearRect(beginX, maxY-a[i], step, a[i]);
                    //ve hinh a[i] moi
                    a[i] =a [j];
                    gr.drawRect(beginX, maxY-a[i], step, a[i]);
                    //xoa hinh a[j] cu
                    
                    beginX2=j*step;
                    gr.clearRect(beginX2, maxY-a[j], step, a[j]);
                    
                    //ve hinh a[i] moi
                    a[j] = temp;
                    gr.drawRect(beginX2, maxY-a[j], step, a[j]);
                }
            }
            beginX += step;
        }
    }//GEN-LAST:event_butsapxepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butsapxep;
    private javax.swing.JButton butvemang1chieu;
    private javax.swing.JPanel pnpanel;
    // End of variables declaration//GEN-END:variables

    public void setLocale(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
